const trailsData = [
    /* ================= RARĂU ================= */
    {
      id: "t1",
      name: "Pietrele Doamnei (Rarău)",
      area: "Câmpulung Moldovenesc",
      difficulty: "Mediu",
      durationHrs: 3.5,
      distanceKm: 8.5,
      season: "Mai–Oct",
      tags: ["view", "forest", "family"],
      url: "https://www.romania.travel/ro/trasee-rarau",
    },
    {
      id: "t2",
      name: "Vârful Rarău – traseu clasic",
      area: "Masivul Rarău",
      difficulty: "Mediu",
      durationHrs: 5,
      distanceKm: 12.2,
      season: "Mai–Oct",
      tags: ["ridge", "view"],
      url: "https://www.romania.travel/ro/muntele-rarau",
    },
    {
      id: "t3",
      name: "Cabana Rarău – Pietrele Doamnei",
      area: "Masivul Rarău",
      difficulty: "Ușor",
      durationHrs: 2,
      distanceKm: 4.8,
      season: "Mai–Oct",
      tags: ["family", "forest"],
      url: "https://www.romania.travel/ro/muntele-rarau",
    },
  
    /* ================= CĂLIMANI ================= */
    {
      id: "t4",
      name: "Călimani – formațiunile 12 Apostoli",
      area: "Vatra Dornei",
      difficulty: "Greu",
      durationHrs: 7,
      distanceKm: 18.4,
      season: "Iun–Sep",
      tags: ["alpine", "long"],
      url: "https://www.romania.travel/ro/calimani",
    },
    {
      id: "t5",
      name: "Vârful Pietrosul Călimani",
      area: "Munții Călimani",
      difficulty: "Greu",
      durationHrs: 8,
      distanceKm: 20,
      season: "Iun–Sep",
      tags: ["alpine", "summit"],
      url: "https://www.romania.travel/ro/calimani",
    },
    {
      id: "t6",
      name: "Lacul Iezer – Călimani",
      area: "Munții Călimani",
      difficulty: "Mediu",
      durationHrs: 4.5,
      distanceKm: 10.6,
      season: "Mai–Sep",
      tags: ["lake", "forest"],
      url: "https://www.romania.travel/ro/calimani",
    },
  
    /* ================= OBICINE ================= */
    {
      id: "t7",
      name: "Obcina Mare – potecă panoramică",
      area: "Marginea",
      difficulty: "Ușor",
      durationHrs: 2.5,
      distanceKm: 6.1,
      season: "Apr–Oct",
      tags: ["view", "relax"],
      url: "https://www.romania.travel/ro/obcinele-bucovinei",
    },
    {
      id: "t8",
      name: "Obcina Feredeu – traseu de creastă",
      area: "Vicovu de Sus",
      difficulty: "Mediu",
      durationHrs: 5,
      distanceKm: 14,
      season: "Mai–Oct",
      tags: ["ridge", "forest"],
      url: "https://www.romania.travel/ro/obcinele-bucovinei",
    },
    {
      id: "t9",
      name: "Obcina Mică – traseu ușor",
      area: "Sucevița",
      difficulty: "Ușor",
      durationHrs: 2,
      distanceKm: 5,
      season: "Apr–Oct",
      tags: ["family", "nature"],
      url: "https://www.romania.travel/ro/obcinele-bucovinei",
    },
  
    /* ================= VATRA DORNEI ================= */
    {
      id: "t10",
      name: "Parcul Central Vatra Dornei – potecă verde",
      area: "Vatra Dornei",
      difficulty: "Ușor",
      durationHrs: 1.5,
      distanceKm: 3,
      season: "Tot anul",
      tags: ["urban", "family"],
      url: "https://www.romania.travel/ro/vatra-dornei",
    },
    {
      id: "t11",
      name: "Dealul Negru – traseu de belvedere",
      area: "Vatra Dornei",
      difficulty: "Mediu",
      durationHrs: 3,
      distanceKm: 7.5,
      season: "Mai–Oct",
      tags: ["view", "forest"],
      url: "https://www.romania.travel/ro/vatra-dornei",
    },
  
    /* ================= HUMOR ================= */
    {
      id: "t12",
      name: "Cheile Moara Dracului",
      area: "Gura Humorului",
      difficulty: "Ușor",
      durationHrs: 2,
      distanceKm: 5.2,
      season: "Apr–Oct",
      tags: ["family", "forest"],
      url: "https://www.romania.travel/ro/gura-humorului",
    },
    {
      id: "t13",
      name: "Pârtia Șoimul – traseu de drumeție",
      area: "Gura Humorului",
      difficulty: "Ușor",
      durationHrs: 1.8,
      distanceKm: 4,
      season: "Apr–Oct",
      tags: ["view", "relax"],
      url: "https://www.romania.travel/ro/gura-humorului",
    },
  
    /* ================= POIANA STAMPEI ================= */
    {
      id: "t14",
      name: "Tinovul Mare Poiana Stampei",
      area: "Poiana Stampei",
      difficulty: "Ușor",
      durationHrs: 1.5,
      distanceKm: 3.2,
      season: "Mai–Sep",
      tags: ["family", "nature"],
      url: "https://www.romania.travel/ro/tinovul-mare",
    },
  
    /* ================= SUCEVIȚA & PUTNA ================= */
    {
      id: "t15",
      name: "Putna – Poiana Teioasa",
      area: "Putna",
      difficulty: "Mediu",
      durationHrs: 4,
      distanceKm: 9.8,
      season: "Mai–Oct",
      tags: ["forest", "culture"],
      url: "https://www.romania.travel/ro/putna",
    },
    {
      id: "t16",
      name: "Sucevița – traseu spre Obcina Mare",
      area: "Sucevița",
      difficulty: "Mediu",
      durationHrs: 4.5,
      distanceKm: 11,
      season: "Mai–Oct",
      tags: ["ridge", "forest"],
      url: "https://www.romania.travel/ro/sucevita",
    },
  ];
  
  export default trailsData;
  